### ISSUE TITLE
Support for the GOBIN environment variable for each Go version.

### ISSUE THREAD

**Issue by BorzdeG** [asdf-community/asdf-golang#107]
By [default](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies), if `GOBIN` is not set, it is not guaranteed that the path `$GOPATH/bin` will be used - it is better to set it explicitly in the Environment

**Comment by ankitcharolia** [comment]
@BorzdeG  Kindly try out this goenv: https://github.com/ankitcharolia/goenv

**Comment by BorzdeG** [comment]
@ankitcharolia Why install something else when it can be solved with one utility?

**Comment by lothar1998** [comment]
@BorzdeG 

I feel like modifying the `set-env.zsh` script can help (of course for ZSH):
```sh
asdf_update_golang_env() {
  local go_path
  go_path="$(asdf which go)"
  if [[ -n "${go_path}" ]]; then
    export GOROOT
    GOROOT="$(dirname "$(dirname "${go_path:A}")")"
    export GOBIN
    GOBIN="$(dirname "$(dirname "${go_path:A}")")/bin"
  fi
}

autoload -U add-zsh-hook
add-zsh-hook precmd asdf_update_golang_env
```

This modification worked for me. Please let me know your thoughts!

**Comment by ctsstc** [comment]
@lothar1998 this is what I was just about to do, but wanted to see what others were doing or if I was the only one with this issue. I ran `go env` and my `GOBIN` is an empty string. I'm still not certain where `go install` is installing to if it's an empty string 🤷  I thought it was supposed to default off of the `GOROOT`, but that seems it may not be the case?

**Comment by lothar1998** [comment]
It seems that it installs the binary into ```$GOROOT/bin``` so I believe the fix I proposed should help. Please take a look at https://github.com/asdf-community/asdf-golang/pull/139.
