### ISSUE TITLE
Google changed golang download URL for golang 1.21

### ISSUE THREAD

**Issue by rg2011** [asdf-community/asdf-golang#121]
**Describe the bug**

The download URL for golang version 1.21 does not follow the same pattern as older versions, it is no longer at `https://dl.google.com`. It is now available at `https://go.dev/dl/`

So this code does not work for installing 1.21:

https://github.com/asdf-community/asdf-golang/blob/d8dec15ccc0cffc2e2762f348ccffeffb79c6489/bin/download#L37

**To Reproduce**

Run `asdf install golang 1.21`:

```
Platform 'linux' supported!
URL: https://dl.google.com/go/go1.21.linux-amd64.tar.gz returned status 404
```

Older versions work fine, e.g.

```bash
$ asdf install golang 1.18
Platform 'linux' supported!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  135M  100  135M    0     0  30.8M      0  0:00:04  0:00:04 --:--:-- 30.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0    408      0 --:--:-- --:--:-- --:--:--   407
verifying checksum
/home/rafa/.asdf/downloads/golang/1.18/archive.tar.gz: OK
checksum verified
```

**Expected behavior**
`asdf install golang 1.21` should install the expected version

**Desktop (please complete the following information):**
 - OS: Ubuntu linux 22.04
 - Browser: dows not apply
 - Version: current master. For reference, it is at commit d8dec15ccc0cffc2e2762f348ccffeffb79c6489

```bash
$ cd ~/.asdf/plugins/golang/ && git rev-parse HEAD
d8dec15ccc0cffc2e2762f348ccffeffb79c6489
```

**Comment by rg2011** [comment]
my mistake, a missed a 0 (`1.21.0`). Sorry!

**Comment by leetrout** [comment]
This is sneaky. Easy to run into. Glad you opened the issue to save me 😂
