### ISSUE TITLE
Unable to install go v1.22 on arm

### ISSUE THREAD

**Issue by vasiliyskysql** [asdf-community/asdf-golang#133]
**Describe the bug**
Am trying to install go v1.22 on m1 mac, am seeing a `URL: https://dl.google.com/go/go1.22.darwin-arm64.tar.gz returned status 404` error.

```
➜  ~ asdf version
v0.14.0
➜  ~ asdf install golang 1.22
Platform 'darwin' supported!
URL: https://dl.google.com/go/go1.22.darwin-arm64.tar.gz returned status 404
```

**To Reproduce**
1. run `asdf install golang 1.22`

**Expected behavior**
go v1.22 is installed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: osx
 - Version 0.14.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vicendominguez** [comment]
brom try it with `asdf install golang 1.22.2` 🙏 (https://go.dev/dl/)
