### ISSUE TITLE
set-env.bash ?

### ISSUE THREAD

**Issue by asmodehn** [asdf-community/asdf-golang#138]
I am using `bash` but there isnt any set-env script for it ? Any specific reason for it ?

I could write a simple one, but I'm not sure how it is supposed to support the various possible setups (go installed on system via distro packages for instance)...

**Comment by ikuwow** [comment]
F.Y.I (workaround)

I'm using the following lines in my .bashrc:

```bash
asdf_update_golang_env() {
  local go_bin_path
  go_bin_path="$(asdf which go 2>/dev/null)"
  if [[ -n "${go_bin_path}" ]]; then
    abs_go_bin_path="$(readlink -f "${go_bin_path}")"

    export GOROOT
    GOROOT="$(dirname "$(dirname "${abs_go_bin_path}")")"

    export GOPATH
    GOPATH="$(dirname "${GOROOT}")/packages"

    export GOBIN
    GOBIN="$(dirname "${GOROOT}")/bin"
  fi
}
asdf_update_golang_env
```

**Comment by samusz** [comment]
This should become `set-env.bash`!

**Comment by ikuwow** [comment]
Thanks for 👍 and ❤️ 
I created pr #147
