### ISSUE TITLE
asdf reshim can't find packages under bin

### ISSUE THREAD

**Issue by x9xhack** [asdf-community/asdf-golang#143]
**Describe the bug**
After latest update "$GOBIN" added to set-env files , asdf reshim can't find go packages under bin folder 

/bin needs to be added to list-bin-path

echo -n "bin go/bin packages/bin"

**Comment by rpadovani** [comment]
Got the same issue on Linux and fish, solved in the same way.

Edit `~/.asdf/plugins/golang/bin/list-bin-paths`, and make sure the line is 

```
echo -n "bin go/bin packages/bin"
```

I opened https://github.com/asdf-community/asdf-golang/pull/146 to fix in the codebase
